### ISSUE TITLE
Doesn't support C++11 or C++14

### ISSUE THREAD

**Issue by lukeeey** [mhsjlw/RakNet#4]
If i set `CMAKE_CXX_STANDARD` to 11 or 14, i get the following errors:

Error with C++11 
```bash
[ 37%] Building CXX object lib/RakNet/CMakeFiles/RakNetStatic.dir/src/ReplicaManager3.cc.o
/sdcard/dev/cpp/Bedrock++/lib/RakNet/src/ReplicaManager3.cc:130:64: error: comparison
      between pointer and integer ('RakNet::Connection_RM3 *' and 'int')
    if (GetConnectionByGUID(participantListIn[index], worldId) == false) {
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~
1 error generated.
make[2]: *** [lib/RakNet/CMakeFiles/RakNetStatic.dir/build.make:2007: lib/RakNet/CMakeFiles/RakNetStatic.dir/src/ReplicaManager3.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:143: lib/RakNet/CMakeFiles/RakNetStatic.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

Error with C++14 (and the above error)
```
/sdcard/dev/cpp/Bedrock++/lib/RakNet/src/Rand.cc:146:3: warning: 'register' storage class
      specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
  register unsigned int *p0 = state, *p2 = state + 2, *pM = state + M, s0, s1;
  ^~~~~~~~~
```

**Comment by mhsjlw** [comment]
Is this a RakNet issue, or something you're doing wrong?

**Comment by mhsjlw** [comment]
I need a line number

**Comment by lukeeey** [comment]
It works perfectly if a dont set cmake to C++ 11 

```
[ 36%] Building CXX object lib/RakNet/CMakeFiles/RakNetStatic.dir/src/ReliabilityLayer.cc.o
[ 37%] Building CXX object lib/RakNet/CMakeFiles/RakNetStatic.dir/src/ReplicaManager3.cc.o
/sdcard/dev/cpp/Bedrock++/lib/RakNet/src/ReplicaManager3.cc:130:64: error: comparison
      between pointer and integer ('RakNet::Connection_RM3 *' and 'int')
    if (GetConnectionByGUID(participantListIn[index], worldId) == false) {
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~
1 error generated.
make[2]: *** [lib/RakNet/CMakeFiles/RakNetStatic.dir/build.make:2007: lib/RakNet/CMakeFiles/RakNetStatic.dir/src/ReplicaManager3.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:143: lib/RakNet/CMakeFiles/RakNetStatic.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
$ sh get
[  1%] Built target jsonxx
[  2%] Building CXX object lib/RakNet/CMakeFiles/RakNetStatic.dir/src/ReplicaManager3.cc.o
/sdcard/dev/cpp/Bedrock++/lib/RakNet/src/ReplicaManager3.cc:130:64: error: comparison
      between pointer and integer ('RakNet::Connection_RM3 *' and 'int')
    if (GetConnectionByGUID(participantListIn[index], worldId) == false) {
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~
1 error generated.
make[2]: *** [lib/RakNet/CMakeFiles/RakNetStatic.dir/build.make:2007: lib/RakNet/CMakeFiles/RakNetStatic.dir/src/ReplicaManager3.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:143: lib/RakNet/CMakeFiles/RakNetStatic.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
$ sh get
```

**Comment by lukeeey** [comment]
Updated.

**Comment by lukeeey** [comment]
Bump

**Comment by mhsjlw** [comment]
What is your toolchain and OS

**Comment by mhsjlw** [comment]
Fixed https://github.com/mhsjlw/RakNet/commit/09bb8922933d216e20854ee325027fe91ff957c5

**Comment by lukeeey** [comment]
I'm still getting an error with the latest commit without changing any code and setting the C++ version to 17

```
Scanning dependencies of target katana
[ 96%] Building CXX object src/CMakeFiles/katana.dir/main.cpp.o
[ 97%] Building CXX object src/CMakeFiles/katana.dir/server/Server.cpp.o
/sdcard/dev/cpp/Katana/src/server/Server.cpp:87:16: error: no matching member function for
      call to 'Send'
                                                if(peer->Send(&value, IMMEDIATE_PRI...
                                                   ~~~~~~^~~~
/sdcard/dev/cpp/Katana/lib/RakNet/include/RakPeerInterface.h:328:20: note: candidate
      function not viable: no known conversion from 'int *' to 'const RakNet::BitStream *'
      for 1st argument
  virtual uint32_t Send(const RakNet::BitStream *bitStream,
                   ^
/sdcard/dev/cpp/Katana/lib/RakNet/include/RakPeerInterface.h:295:20: note: candidate
      function not viable: no known conversion from 'int *' to 'const char *' for 1st
      argument
  virtual uint32_t Send(const char *data, const int length,
                   ^
1 error generated.
make[2]: *** [src/CMakeFiles/katana.dir/build.make:87: src/CMakeFiles/katana.dir/server/Server.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:180: src/CMakeFiles/katana.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

**Comment by mhsjlw** [comment]
That isn't a problem with RakNet, that's a problem with your code. You're not calling Send properly
